# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zjC7dH0_d4SIuCcajiaYj3OvVfRkauvf
"""

import streamlit as st

from textblob import TextBlob

st.set_page_config(page_title="Tweet Sentiment Predictor",layout="wide")




st.title("Airline Tweet Sentiment Predictor")



text = st.text_input("Enter Tweet text:")

if text:
    blob = TextBlob(text)
    sentiment = blob.sentiment.polarity
    if sentiment > 0:
        st.success("Positive 😀")
    elif sentiment < 0:
        st.success("Negative 😔")
    else:
        st.success("Neutral 😐")
  

    polarity_visual = (sentiment + 1) / 2  # Normalize polarity to range [0, 1]
    polarity_scale = st.slider('Polarity Scale', min_value=-1.0, max_value=1.0, value=polarity_visual, step=0.01)