# -*- coding: utf-8 -*-
"""webap

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NK3LET9vfoWaJHlAoBk5yccljgmnivaV
"""

import streamlit as st
from textblob import TextBlob

# Set page configuration
st.set_page_config(page_title="Sentiment Analysis", layout="wide")

# Set app title and description
st.title("Airline Tweet Sentiment Predictor")
st.subheader("Enter Tweet text and check its sentiment!")

# Get user input
text = st.text_input("Enter some text")

if text:
    # Perform sentiment analysis
    blob = TextBlob(text)
    sentiment = blob.sentiment.polarity

    # Determine sentiment label
    if sentiment > 0:
        sentiment_label = "Positive 😀"
    elif sentiment < 0:
        sentiment_label = "Negative 😔"
    else:
        sentiment_label = "Neutral 😐"

    # Display sentiment and emoji
    st.success(f"Sentiment: {sentiment_label}")

    # Display sentiment scale
    st.write("Sentiment Scale:")
    st.write(f'{"Negative":-<20} {"Positive":->20}')
    st.write('|', '-'*int((sentiment + 1) * 20), 'o', '-'*int((1 - sentiment) * 20), '|')

# Note: The scale assumes a sentiment value between -1 and 1, where -1 is fully negative, 1 is fully positive, and 0 is neutral.